import jsPDF from 'jspdf'

export function exportPreferenceListPDF(rows, studentInfo) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const { percentile, rank, category, gender, date } = studentInfo

  // Header
  doc.setFontSize(18)
  doc.setTextColor(255, 0, 0)
  doc.text('FutureU — My CAP Round Preference List', 14, 16)

  doc.setFontSize(10)
  doc.setTextColor(80, 80, 80)
  doc.text(`Percentile: ${percentile ?? '—'} | Rank: ${rank ?? '—'} | Category: ${category ?? '—'} | Gender: ${gender ?? '—'} | Generated: ${date ?? new Date().toLocaleDateString('en-IN')}`, 14, 24)
  doc.text('Sorted from highest predicted cutoff rank (hardest) to lowest (easiest). Fill your preference form in this order.', 14, 30)

  // Table header
  const startY = 36
  const cols = [
    { header: 'Sr.', w: 10 },
    { header: 'Coll. Code', w: 22 },
    { header: 'College Name', w: 76 },
    { header: 'Branch Code', w: 24 },
    { header: 'Branch Name', w: 58 },
    { header: 'Pred. Cutoff (Rank / %)', w: 32 },
    { header: 'Prev. Cutoff (Rank / %)', w: 32 },
    { header: 'Chance', w: 18 },
  ]

  // Draw header row
  let x = 14
  doc.setFillColor(255, 0, 0)
  doc.rect(14, startY, cols.reduce((s, c) => s + c.w, 0), 7, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(9)
  doc.setFont(undefined, 'bold')
  for (const col of cols) {
    doc.text(col.header, x + 2, startY + 5)
    x += col.w
  }

  // Rows
  doc.setFont(undefined, 'normal')
  let y = startY + 7
  const chanceColors = { safe: [22, 163, 74], moderate: [217, 119, 6], reach: [234, 88, 12], unlikely: [255, 0, 0] }

  for (let i = 0; i < rows.length; i++) {
    const row = rows[i]
    if (y > 190) {
      doc.addPage()
      y = 14
    }
    const bg = i % 2 === 0 ? [255, 255, 255] : [249, 250, 251]
    doc.setFillColor(...bg)
    x = 14
    doc.rect(14, y, cols.reduce((s, c) => s + c.w, 0), 6, 'F')
    doc.setTextColor(30, 30, 30)
    
    const predStr = row.predictedRank != null
      ? `${row.predictedRank.toLocaleString()} (${row.predictedPercentile?.toFixed(2)}%)`
      : '—'
    const prevStr = row.previousRank != null
      ? `${row.previousRank.toLocaleString()} (${row.previousPercentile?.toFixed(2)}%)`
      : '—'

    const cells = [
      String(i + 1),
      row.collegeCode ?? '—',
      row.collegeName?.length > 40 ? row.collegeName.substring(0, 40) + '…' : (row.collegeName ?? ''),
      row.branchCode ?? '—',
      row.branchName?.length > 28 ? row.branchName.substring(0, 28) + '…' : (row.branchName ?? ''),
      predStr,
      prevStr,
      row.admissionChance != null ? row.admissionChance + '%' : '—',
    ]
    for (let ci = 0; ci < cols.length; ci++) {
      if (ci === 7 && chanceColors[row.eligibilityStatus]) {
        doc.setTextColor(...chanceColors[row.eligibilityStatus])
        doc.setFont(undefined, 'bold')
      }
      doc.text(cells[ci], x + 2, y + 4)
      doc.setTextColor(30, 30, 30)
      doc.setFont(undefined, 'normal')
      x += cols[ci].w
    }
    y += 6
  }

  // Disclaimer
  doc.addPage()
  doc.setFontSize(9)
  doc.setTextColor(120, 120, 120)
  const disclaimer = [
    'DISCLAIMER',
    'This list is generated by FutureU for informational purposes only.',
    'Predicted cutoffs are based on historical CAP Round data from CET Cell Maharashtra.',
    'Actual cutoffs may vary. Always verify with official DTE Maharashtra / CET Cell sources before filling your preference form.',
    'FutureU is not affiliated with DTE Maharashtra or CET Cell.',
  ]
  let dy = 20
  doc.setFont(undefined, 'bold')
  doc.text(disclaimer[0], 14, dy); dy += 8
  doc.setFont(undefined, 'normal')
  for (let i = 1; i < disclaimer.length; i++) {
    doc.text(disclaimer[i], 14, dy); dy += 7
  }

  doc.save(`FutureU_Preference_List_${new Date().toISOString().slice(0,10)}.pdf`)
}
